[build]
  command = "cd santasa-ivf-redesign && npm install && npm run build"
  publish = "santasa-ivf-redesign/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"